### PR TITLE
Feat/toggle display mode

### PR DESCRIPTION
**Pull request by cheapsteak**

### CODE REVIEW

**Comment by Jephuff** [comment]
Resize doesn't seem to be working, 
image

It should probably also handle smaller screens 
image
a bunch of the columns could definitely shrink.

maybe a separate PR, but the wrapping of the toggle could be improved 
image

**Comment by Jephuff** [comment]
Also could be a separate PR but we should add a selected state to the rows of the table.

**Comment by cheapsteak** [comment]
Good points all  
Tables are (at least currently) second class, mostly there as a teaser for what could be

**Comment by cheapsteak** [comment]
although pushing the content pane out does make it look broken

**Pull request merged**
